### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by CJames1261** [Stefen-Taime/stream-ingestion-redpanda-minio#4]
Hi,

I am new to data science and am trying to follow your repo. In the first code block I am not sure where to find my 'MongoDB connection ID'. I have create a free atlas mongodb account but am not sure where to find my connection ID, if you could please help me out it would be much appreciated, Thanks!

MONGO_CONN_ID = 'mongodb_default'  # Replace with your MongoDB connection ID

**Comment by Stefen-Taime** [comment]
hello which file is it? the code you shared looks like an airflow config

**Comment by CJames1261** [comment]
Wrong project
